export default {
    PROFILE_DATA: "PROFILE_DATA",
    CART_DATA: "CART_DATA",
    CATEGORIES_DATA: "CATEGORIES_DATA",
    PRODUCTS_DATA: "PRODUCTS_DATA",
    LOGOUT: "LOGOUT",
    LOGGED_IN: "LOGGED_IN",
    OPEN_SNACKBAR: "OPEN_SNACKBAR",
    TAB_CHANGE: "TAB_CHANGE",
    BANNER_DATA: "BANNER_DATA"
};